{
  config,
  pkgs,
  inputs,
  modulesPath,
  lib,
  ...
}: {
  imports = [
    # Core modules
    ../modules
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # Hostname
  networking.hostName = "kerberos";

  # Module configuration - Server profile
  hyprland.enable = false;
  floorp.enable = false;
  shell.enable = true;
  docker.enable = true;
  networkmanager.enable = true;
  tailscale.enable = true;
  mullvad.enable = false;
  nvidia.enable = false;
  syncthing.enable = true;
  samba.enable = true;
  pentesting.enable = false;
  ssh.enable = true;
  wallpaper = "/home/ml/pics/wall/wallhaven-jx632y.jpg";

  # Terminal configurations - minimal for server
  terminal = {
    enable = true;
    alacritty.enable = false;
    starship.enable = true;
  };

  # Development tools - server focus
  development = {
    enable = true;
    git.enable = true;
    vscode.enable = false;
    nodejs.enable = true;
    python.enable = true;
  };

  # Utility tools
  utilities = {
    enable = true;
    compression.enable = true;
    text.enable = true;
    system.enable = true;
    nix.enable = true;
  };
  server = {
    immich.enable = true;
    vaultwarden.enable = true;
    traefik.enable = true;
  };

  # Desktop applications - disabled for server
  applications = {
    enable = false;
  };

  # Add any kerberos-specific configuration here

  # Hardware configuration
  # This is usually generated by the NixOS installer
  # You'll need to replace this with the actual hardware configuration
  # from your Hetzner server
  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";

  # File systems
  # Update this section with your actual disk layout
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f6c20247-7d54-4395-8cde-59566053f313";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/0277dfc5-9252-4369-9885-62dd2acf86a1";}
  ];
}
