{
  config,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    # Server base configuration
    ../server/configuration.nix

    # Server-specific modules
    ../server/samba.nix
  ];

  # Hostname
  networking.hostName = "kerberos";

  # Define home-manager configuration
  home-manager.users.ml = import ../server/home.nix;

  # Add any kerberos-specific configuration here

  # Hardware configuration
  # This is usually generated by the NixOS installer
  # You'll need to replace this with the actual hardware configuration
  # from your Hetzner server
  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "xen_blkfront" "vmw_pvscsi"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  # File systems
  # Update this section with your actual disk layout
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2b45afff-45c4-431f-b4ae-db2fb161b762";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/eb30b759e-ebfd-4d18-aaba-ed35e38428f5";}
  ];
  # Boot loader configuration for MBR
  boot.loader.grub.device = "/dev/sda";
}
